services:

  db:
    image: postgres
    restart: always
    container_name: postgreql
    ports:
      - 5432:5432
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    environment:
      # - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    depends_on:
      - db
    build: ./invent
    container_name: Django
    command: sh -c "gunicorn --workers 3 --bind 0.0.0.0:8000 schemas2.wsgi:application"
    # command: sh -c "python manage.py runserver"
    expose: 
    - 8000
    ports:
      - "8000:8000"
    restart: "always"
    
  nginx:
    image: nginx:latest
    volumes:
    # - ./nginx/nginx.conf:/etc/nginx/sites-available/nginx.conf:ro
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']
    # depends_on:
    #   - web