name: CI

on:
    push:
        branches: [ "main" ]

    workflow_dispatch:

jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            - name: "Muestra Mensaje"
              run: "eco hola mundo"