name: CI

on:
    push:
        branches: [ "main" ]

    workflow_dispatch:

jobs:

    build:
        env:
            password: ${{secrets.PASSWORD}}

        runs-on: ubuntu-latest

        steps:
            - name: "Muestra Mensaje"
              run: echo "hola mundo"

            - name: "Muestra variables"
              run: |
                echo "Evento: ${{toJSON(github.event)}}"
                echo "Actor: ${{github.actor}}"